#!/usr/bin/env python3
"""Generate the firmware CSS byte array from the canonical shared stylesheet."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
source = (ROOT / "assets/style.css").read_bytes()
rows = []
for start in range(0, len(source), 16):
    rows.append("    " + ", ".join(f"0x{byte:02x}" for byte in source[start:start + 16]) + ",")
body = "\n".join(rows)
output = f'''/* Generated by tools/embed_style.py; edit assets/style.css. */
#include <stddef.h>
#include <stdint.h>

const uint8_t pocketwiki_style_css[] = {{
{body}
}};
const size_t pocketwiki_style_css_len = {len(source)};
'''
(ROOT / "firmware/main/style_asset.c").write_text(output, encoding="utf-8")
