#!/usr/bin/env python3
"""Generate the firmware pack-management dashboard JavaScript asset."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
source = (ROOT / "assets/manager.js").read_bytes()
rows = []
for start in range(0, len(source), 16):
    rows.append("    " + ", ".join(f"0x{byte:02x}" for byte in source[start:start + 16]) + ",")
body = "\n".join(rows)
output = f'''/* Generated by tools/embed_manager_js.py; edit assets/manager.js. */
#include <stddef.h>
#include <stdint.h>

const uint8_t pocketwiki_manager_js[] = {{
{body}
}};
const size_t pocketwiki_manager_js_len = {len(source)};
'''
(ROOT / "firmware/main/manager_js_asset.c").write_text(output, encoding="utf-8")
