#!/usr/bin/env python3
"""Generate the firmware embedded pack catalogue byte array.

The catalogue served at https://packs.educated.space/index.json is built from
packs/catalog-source.json (in the pocketwiki-content checkout) and published by
tools/publish_pack_catalog.py,
which also copies the exact published bytes to
android/app/src/main/assets/pack_catalog.json. That checked-in copy is the
repo's snapshot of the LIVE catalogue, so it is the correct source for the
firmware: the device verifies downloaded pack sizes and SHA-256s against it,
and those must match the packs actually served. Rebuilding from
catalog-source.json would embed unpublished packs and stale sizes.

The /manage dashboard prefers the live remote index and falls back to this
device-local copy when the browser itself cannot reach packs.educated.space
(for example when the phone is joined to the PocketWiki access point).
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path,
                        default=ROOT / "android" / "app" / "src" / "main" / "assets" / "pack_catalog.json")
    parser.add_argument("--output", type=Path, default=ROOT / "firmware" / "main" / "catalog_asset.c")
    args = parser.parse_args()

    catalog = json.loads(args.source.read_text(encoding="utf-8"))
    if catalog.get("schema") != 1 or not isinstance(catalog.get("packs"), list):
        raise ValueError("published catalogue must use schema 1 and contain packs")

    data = args.source.read_bytes()
    rows = []
    for start in range(0, len(data), 16):
        rows.append("    " + ", ".join(f"0x{byte:02x}" for byte in data[start:start + 16]) + ",")
    body = "\n".join(rows)
    output = f'''/* Generated by tools/embed_catalog.py; edit packs/catalog-source.json and
 * run tools/publish_pack_catalog.py to refresh the published catalogue. */
#include <stddef.h>
#include <stdint.h>

const uint8_t pocketwiki_catalog_json[] = {{
{body}
}};
const size_t pocketwiki_catalog_json_len = {len(data)};
'''
    args.output.write_text(output, encoding="utf-8")
    print(f"Embedded published catalogue with {len(catalog['packs'])} packs "
          f"({len(data)} bytes) at {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
