[platformio]
src_dir = main

[env:esp32-c3]
platform = espressif32@7.0.1
board = esp32-c3-devkitm-1
framework = espidf
extra_scripts =
    pre:pio_pre.py
    post:pio_post.py
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = partitions.csv
board_upload.flash_size = 4MB
build_flags =
    -DCORE_DEBUG_LEVEL=3

[env:esp32-s3]
platform = espressif32@7.0.1
board = esp32-s3-devkitc-1
framework = espidf
extra_scripts =
    pre:pio_pre.py
    post:pio_post.py
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = partitions_16mb.csv
board_upload.flash_size = 16MB
build_flags =
    -DCORE_DEBUG_LEVEL=3
